print("Testing function calls")
PrintResult(f_void(17),"Void function")
PrintResult(f_first(1,2.4,3),"First function")
PrintResult(f_second(1,"hello",4),"Second function")
PrintResult(f_fails(1,"hello"),"Fails ")
